### ISSUE TITLE
Nice naming choice, lol

### ISSUE THREAD

**Issue by GuidoDipietro** [geckolang/gecko#1]
I actually creeped out at first

Renaming the entire project from whatevs to Gecko all of a sudden? I hope you came with the idea before finding my stuff 😛

**Comment by atlx** [comment]
First of all, it's not based off your project, not sure why you'd asume that. If you copyright on your brand feel free to attempt to submit a claim otherwise please refrain from opening issues like this over a project name.

**Comment by atlx** [comment]
Additionally the name of the lang is Gecko vs geckolang (yours), I use geckolang to differentiate the project type.

**Comment by GuidoDipietro** [comment]
Take it easy, I'm not claiming anything. I just found it very funny and I got quite confused at first glance

Good luck and success with your project
